language: perl
env:
  - PERL_TYPE_TINY_XS=0
  - PERL_TYPE_TINY_XS=1
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "blead"
matrix:
  allow_failures:
    - perl: "5.6.1"
    - perl: "5.6.2"
    - perl: "5.8.1"
    - perl: "blead"
  include:
    # Archaic Perls
    - perl: "5.6.1"
      env: PERL_TYPE_TINY_XS=0 
    - perl: "5.6.2"
      env: PERL_TYPE_TINY_XS=0 
    - perl: "5.8.1"
      env: PERL_TYPE_TINY_XS=0
    # Threaded Perls
    - perl: "5.8.9-thr"
      env: PERL_TYPE_TINY_XS=0
    - perl: "5.20.0-thr"
      env: PERL_TYPE_TINY_XS=0
    - perl: "5.20.0-thr"
      env: PERL_TYPE_TINY_XS=1
    # Extended testing on both a Modern and older Perl
    - perl: "5.8.9"
      env: PERL_TYPE_TINY_XS=0 EXTENDED_TESTING=1
      install:
        - cpanm Exporter::Tiny
        - cpanm -n Test::Requires Test::Fatal Test::LeakTrace
        - cpanm -n indirect multidimensional bareword::filehandles strictures
        - cpanm -n Moo Moose Mouse MooseX::Types::Common MouseX::Types::Common
        - cpanm -n match::simple MooseX::Getopt Class::InsideOut Object::Accessor
        - cpanm -n Type::Tie
        - cpan-install --toolchain
        - cpan-install --deps
        - cpan-install --coverage
    - perl: "5.20"
      env: PERL_TYPE_TINY_XS=0 EXTENDED_TESTING=1
      install:
        - cpanm Exporter::Tiny
        - cpanm -n Test::Requires Test::Fatal Test::LeakTrace
        - cpanm -n indirect multidimensional bareword::filehandles strictures
        - cpanm -n Moo Moose Mouse MooseX::Types::Common MouseX::Types::Common
        - cpanm -n match::simple MooseX::Getopt Class::InsideOut Object::Accessor
        - cpanm -n Type::Tie Validation::Class::Simple 
        - cpan-install --toolchain
        - cpan-install --deps
        - cpan-install --coverage
    # Coverage report
    - perl: "5.18"
      env: COVERAGE=1 EXTENDED_TESTING=1
      install:
        - cpanm Exporter::Tiny
        - cpanm -n Test::Requires Test::Fatal Test::LeakTrace
        - cpanm -n indirect multidimensional bareword::filehandles strictures
        - cpanm -n Moo Moose Mouse MooseX::Types::Common MouseX::Types::Common
        - cpanm -n match::simple MooseX::Getopt Class::InsideOut Object::Accessor
        - cpanm -n Type::Tie Validation::Class::Simple 
        - cpan-install --toolchain
        - cpan-install --deps
        - cpan-install --coverage
      script:
        - export PERL_TYPE_TINY_XS=0
        - prove -r -Ilib -Iinc $(test-dirs)
        - export PERL_TYPE_TINY_XS=1
        - prove -r -Ilib -Iinc $(test-dirs)
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - git clone git://github.com/tobyink/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --toolchain
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -r -Ilib -Iinc $(test-dirs)
after_success:
  - export COVERALLS_OPTS=" -select_re '^lib/' "
  - coverage-report
notifications:
  irc:
    channels:
      - "irc.perl.org#moops"
    on_success: change
