language: perl
perl:
  - "5.19"
  - "5.18.1_thr"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
env:
  - EXTENDED_TESTING=1
matrix:
  include:
    - perl: "5.8.1"
      install:
        - "cpanm -n Test::Requires Test::Fatal Test::LeakTrace"
        - "cpanm Exporter::Tiny"
        - "cpanm -n indirect multidimensional bareword::filehandles"
        - "cpanm -n Moo"
    - perl: "5.6.2"
      install:
        - "perl -Idevel.travis -MCPAN -e'install q(PEVANS/Scalar-List-Utils-1.35.tar.gz)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Text::Balanced)'"
        - "perl -Idevel.travis -MCPAN -e'install q(MSCHWERN/ExtUtils-MakeMaker-6.56.tar.gz)'"
        - "perl -Idevel.travis -MCPAN -e'install q(FERREIRA/Exporter-5.63.tar.gz)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Class::ISA)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Test::More)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Test::Harness)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Exporter::Tiny)'"
      script:
        - "HARNESS_IS_VERBOSE=1 perl /home/travis/perl5/perlbrew/perls/5.6.2/bin/prove -r -Ilib -Iinc t"
before_install:
  - "source devel.travis/travis-perlbrew"
  - "perlbrew install-cpanm -f"
  - "perl -V"
install:
  - "cpanm -n Test::Requires Test::Fatal Test::LeakTrace"
  - "cpanm Exporter::Tiny"
  - "cpanm -n indirect multidimensional bareword::filehandles"
  - "cpanm -n Moose MooseX::Types::Common"
  - "cpanm -n Mouse MouseX::Types"
  - "cpanm -n Moo"
  - "cpanm -n Class::InsideOut"
script:
  - "HARNESS_IS_VERBOSE=1 prove -r -Ilib t"
notifications:
  irc:
    channels:
      - "irc.perl.org#moops"
    on_success: change
