language: perl
perl:
  - "5.8.9"
  - "5.8.9_thr"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20.0"
  - "5.20.0_thr"
  - "blead"
matrix:
  include:
    - perl: 5.18.2
      env: COVERAGE=1         # enables coverage+coveralls reporting
    - perl: "5.8.1"
      install:
        - "cpanm -n Test::Requires Test::Fatal Test::LeakTrace"
        - "cpanm Exporter::Tiny"
        - "cpanm -n indirect multidimensional bareword::filehandles"
        - "cpanm -n Moo"
    - perl: "5.6.2"
      install:
        - "perl -Idevel.travis -MCPAN -e'install q(PEVANS/Scalar-List-Utils-1.35.tar.gz)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Text::Balanced)'"
        - "perl -Idevel.travis -MCPAN -e'install q(MSCHWERN/ExtUtils-MakeMaker-6.56.tar.gz)'"
        - "perl -Idevel.travis -MCPAN -e'install q(FERREIRA/Exporter-5.63.tar.gz)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Class::ISA)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Test::More)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Test::Harness)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Exporter::Tiny)'"
      script:
        - "HARNESS_IS_VERBOSE=1 perl /home/travis/perl5/perlbrew/perls/5.6.2/bin/prove -r -Ilib -Iinc t"
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - git clone git://github.com/tobyink/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
before_script:
  - coverage-setup
script:
  - prove -l -j$((SYSTEM_CORES + 1)) $(test-dirs)   # parallel testing
after_success:
  - coverage-report
